on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make perl
            tlmgr update --all
            make
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: MAIN.pdf
